### ISSUE TITLE
Failed to build the osrm image

### ISSUE THREAD

**Issue by jbao** [kirel/intelligent-zoning-engine#15]
Any ideas?    

    Creating osrm_osrm_1
    Attaching to osrm_osrm_1
    osrm_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    osrm_1  |                                  Dload  Upload   Total   Spent    Left  Speed
    100 50.5M  100 50.5M    0     0  6605k      0  0:00:07  0:00:07 --:--:-- 7036k
    osrm_1  | [error] Profile profiles/car.lua not found!
    osrm_1  | [error] Input file /osrm-data/Berlin.osrm not found!
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.ramIndex
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.fileIndex
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.nodes
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.edges
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.geometry
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.timestamp
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.turn_weight_penalties
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.turn_duration_penalties
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.names
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.properties
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.icd
    osrm_1  | [warn] Missing/Broken File: /osrm-data/Berlin.osrm.datasource_names
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.ramIndex" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.fileIndex" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.hsgr" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.nodes" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.edges" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.core" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.geometry" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.timestamp" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.datasource_names" is not found
    osrm_1  | [warn] "" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.names" is not found
    osrm_1  | [warn] "/osrm-data/Berlin.osrm.properties" is not found
    osrm_osrm_1 exited with code 1

**Comment by kirel** [comment]
Neue OSRM-Version offenbar. Mach mal:

```
docker-compose run --rm osrm osrm-extract -p profile.lua /osrm-data/Berlin.osm.pbf
docker-compose run --rm osrm osrm-contract /osrm-data/Berlin.osrm
docker-compose up
```

Der Trick ist, dass `osrm-extract` jetzt mit einem Profil aufgerufen werden muss (-p).
Das müsste in https://github.com/cartography/osrm-backend-docker/blob/master/docker-entrypoint.sh geändert werden, z.B. indem hier eine Version davon per Dockerfile hinzugefügt wird.

**Comment by kirel** [comment]
`curl http://127.0.0.1:5000/route/v2/profile/13.388860,52.517037\;13.385983,52.496891\?steps\=true` sieht gut aus.

**Comment by jbao** [comment]
👍 werde die neue Befehle in den README einfügen.
